### ISSUE TITLE
wifi 型号问题

### ISSUE THREAD

**Issue by tangzhe1996** [emre1393/asus-x555lb-mojave-efi#1]
![图片](https://user-images.githubusercontent.com/32305927/61360526-2ed68800-a8b1-11e9-8d96-2e501a3dede3.png)
您还， 这个WIFI设备是你机器出厂默认的还是后来自己改装的？我百度了一下 搜出来 博通的 BCM94352hmb相关的信息；意思是指这两个设备的驱动文件可以共用的意思吗。还望朋友解答一下

**Comment by emre1393** [comment]
i did not understand your message, i bought aw-ce123h and put into my laptop. 
aw-ce123h is exactly BCM94352hmb as you mentioned, half mini pci-e with bluetooth.
