### ISSUE TITLE
Clover  v 5118

### ISSUE THREAD

**Issue by CMingTseng** [emre1393/asus-x555lb-mojave-efi#4]
Dear Sir

i use Clover  5118

but something is different !!

i do not modify anything  and then i can boot to  install GUI !!
 
Yes  the Keyboard and  touchpad can not work !!! 

but  now  show want me attach  BT mouse & KB !!

____________

i  use your version Clover --- asus-x555lb-mojave-efi

but i get   confusion install GUI !!   maybe bios setting wrong ? or patch /kext error ??

THX

**Comment by emre1393** [comment]
i don't know, i don't have the laptop since a year and i didn't use hackintosh since last commit.
